### ISSUE TITLE
More Scout Clients

### ISSUE THREAD

**Issue by melorium** [vitaly-kamluk/bitscout#15]
Hi again its me disturbing you again. :)

If I want to have more scout client on the same open vpn lan say 10.1.0.4 side and say 10.0.4.1 and 10.0.4.2 (container).

Do I need different ip ( other than 10.0.3.1 and 10.0.3.2)in the lxc containers if I built more than one scout iso that are different form the first one.

The ceritikates I have full control over  and know how to do.

But what do I need to change in the scripts to build a second and third etc... scout image.

I want to use the on the same open vpn server.

Il tried to change ip range in the scrips but I must missed something bee the lxc container didn't start up on the new iso.

Dennis

**Comment by vitaly-kamluk** [comment]
Hi!
You don't have to change IP of the container. The VPN client runs on the host (LiveCD system) and connects to the server. You may want to add new clients names and assign new IPs in /etc/openvpn/scout/ip_pool on the server, but even if you don't it will be assigned automatically. This is just for your convenience and static IP assignment.
Otherwise it shall work, no changes needed. If it doesn't, please do basic tests:
1. Is VPN server IP and port available from LiveCD2 system? Can you ping or scan the port?
2. Look at the openvpn log file in /var/log/openvpn.scout.log
What is in the last lines?

I think your other systems (LiveCD2, LiveCD3,...) shall appear as 10.1.0.4, 10.1.0.5, ... via VPN.

**Comment by melorium** [comment]
Ok so for example if I had a live cd on 10.1.0.4 the host forward 10.1.0.4 to 10.0.3.2 I don't need to change anything. Do I need to make new certificates for every live cd or can I use the same one for LiveCD2, LiveCD3 etc...

Dennis

**Comment by vitaly-kamluk** [comment]
It depends on server's config. You don't need to generate new certificates every time, you can reuse the same ISO to start LiveCD2, LiveCD3, ...
However, in this case you must include the following option in the server's openvpn conf:  
`duplicate-cn`

**Comment by melorium** [comment]
Thanks it Works perfekt.
You can close this case.
Thanks again for your help.
Dennis
