### ISSUE TITLE
UEFI

### ISSUE THREAD

**Issue by melorium** [vitaly-kamluk/bitscout#17]
Hi :)
Do you think its possible to get UEFI work?
Or do you have any good idea how I can try to figure it out for my self.
I love your produkt and use it almost every day.
For forensic work but also for remote recovery of data there the machine didn't start.

Du you know if it any change to mount a NBD device in windows.

I find just a NBD server for windows but not a NBD client.

Thanks again.

Dennis Karlsson

**Comment by vitaly-kamluk** [comment]
Hi Dennis,
I believe the ISO shall be UEFI compatible. We tested it on some configurations with UEFI. Can you describe your issue more precisely? Any error messages seen?

As for NBD client, I am not aware if there is one for Windows. I never had a use case for this. Let me check.

**Comment by melorium** [comment]
Alright.
I remember you enabled something for UEFI and then you rollback it.
But maybe I remember wrong.
I wanted to have it boot from MAC devices.

**Comment by melorium** [comment]
Interesting :)
Whats is the next stage?
Im curious :)

Dennis

**Comment by vitaly-kamluk** [comment]
Hi, Dennis!
Sorry, got distracted by trips. The code was fixed and we made it work for UEFI too. If it doesn’t work can you describe the symptoms?

As for nbd-client for Windows, seems that no one made it. Theoretically it is possible to make it but seems that people who know what it is work on Linux anyway.

**Comment by melorium** [comment]
No problem I will test it all.
But i have a courius question about the next stage in your projekt as you write on the code page.

What are u going to include?

Dennis

**Comment by vitaly-kamluk** [comment]
Hi, there is a list of features and issues to address. If you have any ideas send us via email bitscout(@)kaspersky.com

**Comment by 1wxyz** [comment]
Hi Dennis
I have fix the UEFI problem and tested working on Linux and Windows machines.
Check out the latest build/commit: 0609460 

As I do not have a MAC machine which would be nice if you could test them out for me and report any issues present.

**Comment by melorium** [comment]
Thank you very very much.
I will test it on my Mac.
I LOVE BITSCOUT

Dennis

**Comment by melorium** [comment]
Thank you very very much.
I will test it on my Mac.
I love BITSCOUT.

Dennis

**Comment by melorium** [comment]
THANKS THANKS THANKS.
Now it works on Mac to with UEFI.
You are best Thanks again. :)

**Comment by melorium** [comment]
I test it on every machine i have and it work great.
I test it on older and new macs also. 
All my 15 older and new laptops and ever the new imac pro.
It boots on every machine il tried.
How did you do that you are amazing😊😊😊😊😊
Thanks

**Comment by 1wxyz** [comment]
@melorium 
The detailed changes are mentioned on this commit 0609460 and d805303

1. 0609460: Basically I imported 2 EFI modules on grub.cfg file, namely the EFI graphics modules for grub2, efi_gop (graphics output protocol) and efi_uga (universal graphics adapter) [Source:https://help.ubuntu.com/community/UEFIBooting]

2. d805303: There is another problem which I discovered when booting bitscout using a USB stick on an EFI system, which will stuck at grub rescue menu. The problem was simply solved by loading part_gpt module on grub-mkrescue. Thus during the initial booting process, grub will be able to look for /boot/grub/grub.cfg file on a GPT-based partition.

I am happy it works for you now.
