### ISSUE TITLE
Wifi on the new Builds

### ISSUE THREAD

**Issue by melorium** [vitaly-kamluk/bitscout#19]
Hi the new builds don't finds any wifi when I boot up and seach for wifi.

no wireless found is the answer and I tried it on several desktops and laptops.

Why is what do you think?

Dennis

**Comment by vitaly-kamluk** [comment]
Hi Dennis,
Thank you for reporting!
I noticed this recently as well. It seems that wifi modules were moved to optional package linux-modules-extra which isn’t installed by default with the kernel now.
This has been fixed in the latest commit. Please check and confirm that it works for you now. 

By the way, we are planning to do Bitscout training for advanced users in April 2018 in Singapore. More details at https://sas.kaspersky.com

**Comment by vitaly-kamluk** [comment]
Should be fixed by 92d8f34043875ecf752658898becd720fce55a35
Please reopen if happens again.
