### ISSUE TITLE
Port 2000

### ISSUE THREAD

**Issue by melorium** [vitaly-kamluk/bitscout#21]
Hi I can't reach port 2000 from my WS into bitscout.

I using this command sudo nbd-client -N dvd 10.1.0.2 2000 /dev/nbd0

And telnet 10.1.0.2 don't answer either.

I can ssh into the container without any problem.

Have you changed the port 2000 to 2009 ?

Dennis

**Comment by melorium** [comment]
It seems that port 2000 are blocked from outside.

**Comment by vitaly-kamluk** [comment]
It seems that it comes from changes in upstream LXD package: it started attaching another virtual network interface by default to every container and it broke existing setup. This is fixed in the latest update. I also added a test condition to detect such things in the future. Please check now and thanks for reporting!

**Comment by melorium** [comment]
Thanks I will try it again.

I really like your software.

I will try to book in your event in April I will be so exiting to meet you.

But do you think my skills will be enough to understand what you will learn out?

Dennis

**Comment by vitaly-kamluk** [comment]
We will teach basic and advanced things using Bitscout, we will use nbd in quite unusual ways, which might be interesting to you. If you worked with linux commandline that will help, but you obviously have time to make yourself familiar with tools we will use, because the training is only in April next year. 

Here is some guidelines for self-learning and preparation:
Learn to install new packages using apt or apt-get in terminal. Learn to work with filesystem and processes on Linux commandline using basic commands such as ls, cd, mv, cp, cat, hexdump, xxd, hexedit, base64, gzip, grep, sed, awk, indent, iconv, mount, ps, kill. Try powerful text editor such as vim, or pick your other favourite. Install and try some of specialised tools we will use:
ssh and scp
smbd
tmux
losetup
mknod
mkfifo
blockdev
parted and fdisk
dd
mmls, fls, icat, other tools from sleuthkit
gdb
volatility
qemu-img
qemu-system*
nbd-server
xnbd-client
nasm

Write a couple of scripts in python and read about fuse drivers.

That should make your training efficient. 
And it would be nice to meet you in person.

**Comment by melorium** [comment]
Works Perfekt now.

Thanks :)

I will book up that course. What is the most easy way to do it?

Thanks again

**Comment by vitaly-kamluk** [comment]
Nice, thanks for confirmation! Let me close this issue. 
As for the training, I think you need to fill small form on the website to apply: https://sas.kaspersky.com/#gform_wrapper_4
