### ISSUE TITLE
having a few ISO build issues

### ISSUE THREAD

**Issue by kapshure** [vitaly-kamluk/bitscout#31]
Hi, I am excited to try out this tool, after having seen it on a SANS webinar..  However, I am having a few issues on getting the ISO built correctly, was hoping I could solicit some help :) 

1)  OpenVPN configuration
Admittedly, I had also grabbed the 20.04 release, instead of 18.04, which is what my Ubuntu VM is on. 
Probably something basic, I must be missing something

```
Generating export files packages..
Copying files for the server..
'./config/openvpn/scout.conf.server' -> 'exports/server/etc/openvpn/server.conf'
'./config/openvpn/ip_pool.lst' -> 'exports/server/etc/openvpn/scout/ip_pool.lst'
'./config/openvpn/easy-rsa/pki/ta.key' -> 'exports/server/etc/openvpn/scout/ta.key'
cp: cannot stat './config/openvpn/easy-rsa/pki/dh.pem': No such file or directory
cp: cannot stat './config/openvpn/easy-rsa/pki/private/server.key': No such file or directory
cp: cannot stat './config/openvpn/easy-rsa/pki/issued/server.crt': No such file or directory
cp: cannot stat './config/openvpn/easy-rsa/pki/ca.crt': No such file or directory
'./config/ngircd/ngircd.conf' -> 'exports/server/etc/ngircd/ngircd.conf'
Copying files for the expert host..
'./config/openvpn/scout.conf.expert' -> 'exports/expert/etc/openvpn/expert.conf'
'./config/openvpn/easy-rsa/pki/ta.key' -> 'exports/expert/etc/openvpn/scout/ta.key'
cp: cannot stat './config/openvpn/easy-rsa/pki/private/expert.key': No such file or directory
cp: cannot stat './config/openvpn/easy-rsa/pki/issued/expert.crt': No such file or directory
cp: cannot stat './config/openvpn/easy-rsa/pki/ca.crt': No such file or directory
'./config/ssh/scout' -> 'exports/expert/etc/ssh/scout'
'./config/ssh/scout.pub' -> 'exports/expert/etc/ssh/scout.pub'
```
2) when I run the autotest.sh script, I get this error message:
`autotest: Timeout expired while waiting for login prompt. System boot: ERROR`
this wouldn't have anything to do with the previous issue would it?

here are the (2) automake/autotest log files:
[autotest.log](https://github.com/vitaly-kamluk/bitscout/files/5562866/autotest.log)
[automake.log](https://github.com/vitaly-kamluk/bitscout/files/5562867/automake.log)

**Comment by vitaly-kamluk** [comment]
Hey kapshure, thanks for reporting the issue! 
1. It seems you are trying to build Bitscout 20.04 on Ubuntu 18.04. While this is not impossible, it may require some manual fixing. Your problem comes with easy-rsa package for Ubuntu. The reason is likely related to major difference of EasyRSA used in Ubuntu 18.04 and Ubuntu 20.04. In the latest Ubuntu 20.04 they moved to a new version of EasyRSA and that changed many scripts, config files and their location. This has been reflected in Bitscout 20.04 which now suports building only on the latest EasyRSA used in Ubuntu 20.04.
You can see this problem appears with OpenVPN configuration according to your logs:
> Configuring OpenVPN..
> Checking if file (filelist) exists..
> **File is NOT FOUND: config/openvpn/easy-rsa/pki/issued/client.crt**
> Preparing OpenVPN configs based on templates..
> 'resources/openvpn/ip_pool.lst' -> 'config/openvpn/ip_pool.lst'
> Setting up OpenVPN client..
> Couldn't find existing Easy-RSA directory in config/openvpn.
> Copying easy-rsa directory to local configs subdirectory..
> Preparing Easy-RSA 3 settings..
> **cp: cannot stat 'config/openvpn/easy-rsa/vars.example': No such file or directory**
> Patching easy-rsa tools to enable non-interactive mode by default.
> Creating certificate authority and server+client certificates..
> 1+0 records in
> 1+0 records out
> 1024 bytes (1.0 kB, 1.0 KiB) copied, 0.000211093 s, 4.9 MB/s
> **scripts/chroot_configure_openvpn.sh: line 63: ./easyrsa: No such file or directory**
> **scripts/chroot_configure_openvpn.sh: line 64: ./easyrsa: No such file or directory**
> **scripts/chroot_configure_openvpn.sh: line 65: ./easyrsa: No such file or directory**
> ...

On the other hand, if you are NOT planning to use OpenVPN for real remote work, you may just ignore this, because your ISO was build fine according to the logs. You may try working in a console or conenct directly over SSH.

If you still want to have complete Bitscout with OpenVPN, you may try building on Ubuntu 20.04, i.e. in a VM running Ubuntu 20.04. Alternatively you can always try older branch of Bitscout 18.04 that used to build on Ubuntu 18.04.

2. Autotest.sh failure is not critical too. There is reasonable timeout for logon prompt and other things. Sometimes on slower CPUs or inside VM it may take longer to boot an ISO which leads to timeout expiry. This seems like your case. You may try increasing the timeout inside ./resources/autotest/basic.exp. Just look for several lines with "set timeout 120". Increase the value of timeout in second to something bigger if you like. But note, that one of the tests will check if OpenVPN is running, so you may have a failure report if you haven't solved the first issue above. Feel free to ignore it and try the ISO by booting it in a VM or on  a real machine and a USB drive.

Good luck and let me know how you choose to resolve your issue!
