### ISSUE TITLE
package installation issue

### ISSUE THREAD

**Issue by brightpinefield** [vitaly-kamluk/bitscout#37]
Trying to install packages within Bitscout gave me this and I'm wondering if there's a way to get around it?

<img width="857" alt="packageissue" src="https://github.com/vitaly-kamluk/bitscout/assets/62759487/574aede3-c951-48f8-b6a5-1ac0ae5ae27a">

**Comment by vitaly-kamluk** [comment]
Hey, that sounds like a broken dependency issue. This may happen due to obsolete packages that a package depends on. Usually it's fixed by the package maintainers once someone reports the issue. I just did `apt update && apt install tesseract-ocr` on a Bitscout instance and it worked like a charm. Just make sure you run `apt update` before installing a package when you see such an issue.
Please confirm and, if resolved, close the issue. Thanks!

**Comment by brightpinefield** [comment]
This is working now.  I guess the maintainers fixed the issue.  Thanks!
