### ISSUE TITLE
Bitscout is not forensically sound

### ISSUE THREAD

**Issue by msuhanov** [vitaly-kamluk/bitscout#4]
The following issue has been discovered: when an unclean (dirty) Ext4 file system is present on a fixed drive, it is recovered by Bitscout during the boot; see the attached screenshot and a sample file system image.
![bitscout](https://user-images.githubusercontent.com/7497142/28017160-de8fcafe-6588-11e7-833e-b461f4699926.png)
[ext4-dirty.raw.gz](https://github.com/vitaly-kamluk/bitscout/files/1135368/ext4-dirty.raw.gz)

The issue can be also reproduced when running Bitscout on real hardware, and when a sample file system is inside a partition.

**Comment by vitaly-kamluk** [comment]
Valuable finding! Can you suggest a fix?

**Comment by vitaly-kamluk** [comment]
Thanks for reporting this!
I fixed that by modifying Ubuntu casper system used in Bitscout. Now casper finds the livefs media via unique disk label rather than by mounting all available filesytems. The unique disk label is chosen randomly when the first build process starts.

Confirmed behavior before patch:
![bitscout_before_patch](https://user-images.githubusercontent.com/1012671/28025054-da8afc5a-6581-11e7-9b90-6669c223e7c0.png)

After patch was applied and ISO was rebuilt:
![bitscout_after_patch](https://user-images.githubusercontent.com/1012671/28025090-f535b6c6-6581-11e7-8205-8101e1c2c4a4.png)

The risk of tampering unclean filesystems by the expert shall not be present, because the expert has access only to the read-only loop block devices.

**Comment by msuhanov** [comment]
> The risk of tampering unclean filesystems by the expert shall not be present, because the expert has access only to the read-only loop block devices.

It seems that the guest container doesn't have permission to mount a block device. But if you ever allow the guest container to mount a loop device (for example, to preview file systems on a suspect machine), the read-only loop device won't protect against modifications in some cases.

**Comment by vitaly-kamluk** [comment]
Yes, correct. Right now guest container is allowed to use fuse filesystem drivers only (i.e. ntfs-3g), but we need a better mechanism to moount some rare filesystems which has no fuse drivers. Do you suggest to apply kernel patch for write blocking? If so, can certain devices be unlocked for modification if the system owner asks for malware removal?

**Comment by msuhanov** [comment]
> Do you suggest to apply kernel patch for write blocking? If so, can certain devices be unlocked for modification if the system owner asks for malware removal?

Yes (to both questions). I saw that you have noticed my kernel patch and userspace tools, they provide a way to control the write blocker through the _blockdev_ tool.

**Comment by vitaly-kamluk** [comment]
Awesome job with that kernel patch and tools, Maxim! I am integrating it into the build process and let people use it in Bitscout. Thank you for your research in this field!
