### ISSUE TITLE
Kbd Package

### ISSUE THREAD

**Issue by noelgeorge93** [vitaly-kamluk/bitscout#7]
Hi, While running the ./automake.sh , I encountered an error stating "Failed to locate kbd package to patch"
I tried running it on vmware and from usb live.Can someone help me on this?

**Comment by vitaly-kamluk** [comment]
Seems like you are missing an important package (called kbd). Can you send the full output of automake.sh to bitscout[at]kaspersky.com?

**Comment by vitaly-kamluk** [comment]
According to some reports this may be related to build process which was started on the offline system. Please note that you need access to the internet to be able to download Ubuntu packages from the official servers of the vendor. 
If you see the following build output lines, it may indicate your network connectivity problem:  
`...`  
`I: Retrieving InRelease`  
`I: Failed to retrieve InRelease`  
`...`

**Comment by aoprea1982** [comment]
// If you see the following build output lines, it may indicate your network connectivity problem:

Hi, i dont have network connectivity problems but i saw the following:

/*      Fixing keyboard-configuration GDM compatibility bug (divert kbd_mode)..
         Failed to locate kbd package to patch. Aborting..
*/

kbd is installed , tried with kali and ubuntu both on vmware

**Comment by aoprea1982** [comment]
Error seen
![bitscout8](https://user-images.githubusercontent.com/16059481/29851578-c9264f62-8d6f-11e7-9122-8c21241033b3.jpg)

chroot_download.sh
![bitscout7](https://user-images.githubusercontent.com/16059481/29851577-c9263946-8d6f-11e7-9b7e-4a93b70cab0f.jpg)

Internet Access
![bitscout9](https://user-images.githubusercontent.com/16059481/29851579-c92871ca-8d6f-11e7-8ec8-5fe627fc117d.jpg)

**Comment by vitaly-kamluk** [comment]
Can you copy/paste the whole log above this error?

**Comment by aoprea1982** [comment]
> Can you copy/paste the whole log above this error?
Uploaded your requested info. (Ubuntu 64 bit)
![vitaly](https://user-images.githubusercontent.com/16059481/29928845-e2d5c43e-8ea4-11e7-90cc-732efc312d68.jpg)


> Commented out the lines referring to "kbd" and it created the ".iso" but it was only 5megs and couldnt boot from it.

**Comment by aoprea1982** [comment]
Debian 32 bit 
![vitaly1](https://user-images.githubusercontent.com/16059481/29929728-3aa83262-8ea7-11e7-80b6-27102f08237e.jpg)

Thanks.

**Comment by vitaly-kamluk** [comment]
Hi!
Your problem was related to missing apt-fast. Check your screenshots above. The reason is that recent Bitscout uses apt-fast tool to download deb packages in multi-threaded mode. Apt-fast has to be downloaded from a separate repository. This could be done automatically if you ran `git clone --recursive https://github.com/...` instead of normal `git clone https://github.com/...`.  
  
Anyway, you'd better try the new version of Bitscout, which downloads these dependencies automatically now. There are some major important updates, including write-blocker patch for Linux kernel. I strongly recommend to use that one in serious investigations. **Beware, using custom kernel may significantly increase Bitscout build time (up to 3+ hours on some older systems)!**  
Feel free to not use custom kernel if you want just a quick demo or play with the tool in the lab.

**Comment by aoprea1982** [comment]
Thanks Vitaly for your prompt actions. 
![bitscout12](https://user-images.githubusercontent.com/16059481/30022538-aea74354-91a6-11e7-8728-dfbed6b96a0e.jpg)
Sorry for the dumb question. Didnt notice apt-fast error in the logs.
It worked .

**Comment by vitaly-kamluk** [comment]
Glad to hear that! I see you chose the minimal version. The medium is more useful and doesn't always need internet connection. Certain most essential software is on it, but you can always make your own selection, just modify scripts/chroot_install_base.sh where you see the list of packages. Good luck!
