### ISSUE TITLE
Image from host to expert ?

### ISSUE THREAD

**Issue by melorium** [vitaly-kamluk/bitscout#9]
Everything works fine with the vpn server now.
But I have some questions if its ok.

1. If I want to create a image from the host (scout) to the experts machine to a mount point of the experts machine what do I need to do?
 I have my expert machine here with me and a big NAS mounted on it.
 
I want to image the scouts machine (the one I sent the usb iso to) home to my expert machine.

So the scenario for me is.
1. Scout machine on 10.1.0.2 fare away from me
2. Expert machine with me on 10.1.0.3 there I want to store the iso from scout machine
3. The vpn Server up and running.

Dennis Karlsson

**Comment by vitaly-kamluk** [comment]
Dennis, there are mutliple ways of doing this. If your network is stable you can start from using simple commands like netcat (nc), dd and gzip.  
1. You map the drive on the host from /dev/sda (for example) to evidence0.
2. On the container (10.1.0.2) you run: `dd if=/dev/host/evidence0 | gzip -c | nc -l -p 2000`
3. On the expert base machine (10.1.0.3) you just need to connect to the container over vpn and grab the compressed image, optionally decompressing it, i.e.:
`nc 10.1.0.1 2000|gzip -dc >your/local/path/image.dd`

Play with this commands and if you are good with it learn how to use dc3dd instead of dd to hash the image, use pv command to monitor the progress, etc. Read man pages if not sure about the option and search online for best practice.

Good luck!

**Comment by vitaly-kamluk** [comment]
Sorry 10.1.0.1 shall be 10.1.0.2.

**Comment by vitaly-kamluk** [comment]
This is explained here: https://github.com/vitaly-kamluk/bitscout/wiki/Advanced-Usage
